### PR TITLE
Implement Funtionality on Like Button 

### PR DESCRIPTION
**Pull request by RitaDee**
### In this milestone, I implemented the following:

- When the user clicks on the Like button of an item, the interaction is recorded in the Involvement API and the screen is updated.

### CODE REVIEW

**Review by shaaibu7 — CHANGES_REQUESTED** [review]
Great job done so far :+1: 

kindly add a readme file for your project.

**Comment by RitaDee** [comment]
> Great job done so far 👍
> 
> kindly add a readme file for your project.

Noted with so much thanks 😊

**Review by shaaibu7 — APPROVED** [review]
Congratulations there is nothing to say else it's time to merge :100: 

Cheers and happy coding...

**Comment by RitaDee** [comment]
> Congratulations there is nothing to say else it's time to merge 💯
> 
> Cheers and happy coding...

🙏

**Pull request merged**
